CREATE TABLE ARTICULO (
       COD_ARTICULO VARCHAR(5) NOT NULL UNIQUE,
       ID_DESPEN VARCHAR(50) UNIQUE,
       NOM_ARTICULO VARCHAR(50) NOT NULL UNIQUE,
       SUPERMERCADO VARCHAR(50) ,
       PRECIO VARCHAR(3) ,
       FEC_CAD_ART DATE ,
       CANTIDAD VARCHAR(4),
       PRIMARY KEY (COD_ARTICULO)
);

CREATE TABLE LISTA(
       COD_LISTA VARCHAR(50) NOT NULL UNIQUE,
       NOM_US VARCHAR(50) NOT NULL UNIQUE,
       COD_ARTICULO VARCHAR(50) NOT NULL UNIQUE,
       PRIMARY KEY (COD_LISTA)
);

CREATE TABLE USUARIO (
       NOM_US VARCHAR(50) NOT NULL UNIQUE,
       ID_DESPEN VARCHAR(50) UNIQUE,
       COD_LISTA VARCHAR(50) UNIQUE,
       PASS_US VARCHAR(50) NOT NULL UNIQUE,
       EMAIL_US VARCHAR(50),
       PRIMARY KEY (NOM_US)
);

CREATE TABLE DESPENSA(
       ID_DESPEN VARCHAR(50) NOT NULL UNIQUE,
       NOM_US VARCHAR(50) NOT NULL UNIQUE,
       PRIMARY KEY (ID_DESPEN)
);

CREATE TABLE LISTA_ARTICULO(
      
       COD_LISTA VARCHAR(50) NOT NULL UNIQUE,
       COD_ARTICULO VARCHAR(5) NOT NULL UNIQUE,
       PRIMARY KEY (COD_LISTA,COD_ARTICULO)
);

ALTER TABLE LISTA ADD FOREIGN KEY (NOM_US) REFERENCES USUARIO (NOM_US);
ALTER TABLE LISTA ADD FOREIGN KEY (COD_ARTICULO) REFERENCES ARTICULO (COD_ARTICULO);

ALTER TABLE USUARIO ADD FOREIGN KEY (ID_DESPEN) REFERENCES DESPENSA (ID_DESPEN);
ALTER TABLE USUARIO ADD FOREIGN KEY (COD_LISTA) REFERENCES LISTA (COD_LISTA);

ALTER TABLE DESPENSA ADD FOREIGN KEY (NOM_US) REFERENCES USUARIO (NOM_US);

ALTER TABLE LISTA_ARTICULO ADD FOREIGN KEY (COD_LISTA) REFERENCES LISTA (COD_LISTA);
ALTER TABLE LISTA_ARTICULO ADD FOREIGN KEY (COD_ARTICULO) REFERENCES ARTICULO (COD_ARTICULO);